services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - BASE_URL=http://localhost:8080
    ports:
      - "8000:80"
