name: style_transfer
description: "Style Transfer App."

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  camera: ^0.11.0
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^14.1.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.10
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/app/assets
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter_launcher_icons:
  image_path: "logo.jpeg"
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: "logo.jpeg"
